theme: jekyll-theme-slate
title: Engineering Online Experimentation
description: Architecture, Pipelines, and Statistical Methods for Production-Scale Systems
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter_opts:
    disable: true
defaults:
  - scope:
      path: ''
    values:
      layout: 'default'
